local CraftingRecipes = {}

CraftingRecipes.Pistol = {
	parts = {
		{ id = "PistolBarrel", display = "Barrel", letter = "B" },
		{ id = "PistolClip", display = "Clip", letter = "C" },
		{ id = "PistolGrip", display = "Grip", letter = "G" },
		{ id = "PistolUpperBody", display = "Upper Body", letter = "U" },
		{ id = "PistolLowerBody", display = "Lower Body", letter = "L" },
		{ id = "PistolHammer", display = "Hammer", letter = "H" },
	},
}

return CraftingRecipes
